<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function  getAllSourtedByCreated(){
        $query = $this->createQueryBuilder('p')
        ->orderBy('p.createdAt', 'DESC')
        ->addOrderBy('p.id', 'DESC')
        ->getQuery();

        $posts = $query->getResult();

        return $posts;
    }
}
